# Generated by Django 4.0.4 on 2024-03-25 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='adresse',
            new_name='infos',
        ),
    ]
