# Generated by Django 4.0.4 on 2024-03-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0004_alter_transaction_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raison_rend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.CharField(max_length=100)),
            ],
        ),
    ]
