# Generated by Django 4.0.4 on 2024-03-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0005_raison_rend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Raison_rend',
        ),
    ]
