# Generated by Django 4.0.4 on 2024-03-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0008_remove_patient_age_patient_date_de_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='indicatif_telephonique',
            field=models.CharField(choices=[('+212', '+212 (Maroc)'), ('+1', '+1 (USA)'), ('+33', '+33 (France)'), ('+44', '+44 (Royaume-Uni)'), ('+49', '+49 (Allemagne)'), ('+81', '+81 (Japon)'), ('+86', '+86 (Chine)'), ('+91', '+91 (Inde)'), ('+34', '+34 (Espagne)'), ('+39', '+39 (Italie)'), ('+61', '+61 (Australie)'), ('+7', '+7 (Russie)'), ('+52', '+52 (Mexique)'), ('+1', '+1 (Canada)'), ('+82', '+82 (Corée du Sud)'), ('+971', '+971 (Émirats arabes unis)'), ('+966', '+966 (Arabie saoudite)'), ('+65', '+65 (Singapour)'), ('+351', '+351 (Portugal)'), ('+852', '+852 (Hong Kong)')], default='+212', max_length=5),
        ),
    ]
