# Generated by Django 4.0.4 on 2024-03-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0009_patient_indicatif_telephonique'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='CIN',
            field=models.CharField(default='AB786473', max_length=50),
        ),
    ]
