# Generated by Django 4.0.4 on 2024-02-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0012_rend_la_date_rend_raison'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rend',
            old_name='choix',
            new_name='Ancien_patient',
        ),
        migrations.AddField(
            model_name='rend',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
