# Generated by Django 4.0.4 on 2024-03-17 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0013_rename_choix_rend_ancien_patient_rend_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='rend',
            name='L_Heure',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
