# Generated by Django 4.0.4 on 2024-03-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0015_rend_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rend',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
